main: main.cpp binary_search_tree.cpp
	g++ main.cpp binary_search_tree.cpp -Wall -pedantic -o main

test: binary_search_tree.cpp tree_test.cpp
	g++ binary_search_tree.cpp tree_test.cpp -Wall -pedantic -o tree_test