name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make lab1
      working-directory: ./lab1
      run: make
    - name: make lab2
      working-directory: ./lab2
      run: make
    
    
