name: build-and-test

on: push

jobs:
  buildandtest:
    name: Build and test the program
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build and test
        run: |
          cd lab7
          make main_cov
          ./test
          
      - name: Codecov
        run: cd lab7 && export CODECOV_TOKEN="6ba79214-6cbd-49ed-83af-af6ab2ab06b2" && bash <(curl -s https://codecov.io/bash)
