name: build-and-test

on: push

jobs:
  buildandtest:
    name: Build and test the program
    
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build and test
        working-directory: ./lab7
        run: make main_cov
          
      - name: Codecov
        run: curl -s https://codecov.io/bash | bash -s - -t token | export CODECOV_TOKEN="6ba79214-6cbd-49ed-83af-af6ab2ab06b2"
